name: Release Controller Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
      # Override registry if needed; Makefile defaults to ghcr.io/arxignis/ingress-nginx
      REGISTRY: ghcr.io/arxignis/ingress-nginx
      # Ensure Makefile uses the Git tag as image tag
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch controller images
        run: |
          make release

